[gitlab_ansible]
fentuan-gitlab_ansible-0_1 ansible_ssh_host=10.8.0.1

[elasticsearch]
fentuan-elasticsearch-0_56 ansible_ssh_host=10.10.0.56
fentuan-elasticsearch-0_55 ansible_ssh_host=10.10.0.55

[bee]
fentuan-bee-19_231 ansible_ssh_host=10.4.19.231
fentuan-bee-20_3 ansible_ssh_host=10.4.20.3
fentuan-bee-19_253 ansible_ssh_host=10.4.19.253
fentuan-bee-19_255 ansible_ssh_host=10.4.19.255
fentuan-bee-20_7 ansible_ssh_host=10.4.20.7
fentuan-bee-19_205 ansible_ssh_host=10.4.19.205
fentuan-bee-19_221 ansible_ssh_host=10.4.19.221
fentuan-bee-19_203 ansible_ssh_host=10.4.19.203
fentuan-bee-19_227 ansible_ssh_host=10.4.19.227
fentuan-bee-20_6 ansible_ssh_host=10.4.20.6
fentuan-bee-20_4 ansible_ssh_host=10.4.20.4
fentuan-bee-19_198 ansible_ssh_host=10.4.19.198
fentuan-bee-19_206 ansible_ssh_host=10.4.19.206
fentuan-bee-19_222 ansible_ssh_host=10.4.19.222
fentuan-bee-19_228 ansible_ssh_host=10.4.19.228
fentuan-bee-20_2 ansible_ssh_host=10.4.20.2
fentuan-bee-19_235 ansible_ssh_host=10.4.19.235
fentuan-bee-19_233 ansible_ssh_host=10.4.19.233
fentuan-bee-19_250 ansible_ssh_host=10.4.19.250
fentuan-bee-20_5 ansible_ssh_host=10.4.20.5
fentuan-bee-19_234 ansible_ssh_host=10.4.19.234
fentuan-bee-20_0 ansible_ssh_host=10.4.20.0
fentuan-bee-20_1 ansible_ssh_host=10.4.20.1
fentuan-bee-19_200 ansible_ssh_host=10.4.19.200
fentuan-bee-19_202 ansible_ssh_host=10.4.19.202
fentuan-bee-19_199 ansible_ssh_host=10.4.19.199
fentuan-bee-19_226 ansible_ssh_host=10.4.19.226
fentuan-bee-19_218 ansible_ssh_host=10.4.19.218
fentuan-bee-20_8 ansible_ssh_host=10.4.20.8
fentuan-bee-19_201 ansible_ssh_host=10.4.19.201
fentuan-bee-19_251 ansible_ssh_host=10.4.19.251
fentuan-bee-19_225 ansible_ssh_host=10.4.19.225
fentuan-bee-19_204 ansible_ssh_host=10.4.19.204
fentuan-bee-19_224 ansible_ssh_host=10.4.19.224
fentuan-bee-19_223 ansible_ssh_host=10.4.19.223
fentuan-bee-19_229 ansible_ssh_host=10.4.19.229
fentuan-bee-19_252 ansible_ssh_host=10.4.19.252
fentuan-bee-19_217 ansible_ssh_host=10.4.19.217
fentuan-bee-19_219 ansible_ssh_host=10.4.19.219
fentuan-bee-19_220 ansible_ssh_host=10.4.19.220
fentuan-bee-19_236 ansible_ssh_host=10.4.19.236
fentuan-bee-19_232 ansible_ssh_host=10.4.19.232
fentuan-bee-19_230 ansible_ssh_host=10.4.19.230
fentuan-bee-19_254 ansible_ssh_host=10.4.19.254

[newbee]
fentuan-bee-20_38 ansible_ssh_host=10.4.20.38
fentuan-bee-20_22 ansible_ssh_host=10.4.20.22
fentuan-bee-20_35 ansible_ssh_host=10.4.20.35
fentuan-bee-20_20 ansible_ssh_host=10.4.20.20
fentuan-bee-20_24 ansible_ssh_host=10.4.20.24
fentuan-bee-20_23 ansible_ssh_host=10.4.20.23
fentuan-bee-20_33 ansible_ssh_host=10.4.20.33
fentuan-bee-20_36 ansible_ssh_host=10.4.20.36
fentuan-bee-20_21 ansible_ssh_host=10.4.20.21
fentuan-bee-20_16 ansible_ssh_host=10.4.20.16
fentuan-bee-20_17 ansible_ssh_host=10.4.20.17
fentuan-bee-20_18 ansible_ssh_host=10.4.20.18
fentuan-bee-20_32 ansible_ssh_host=10.4.20.32
fentuan-bee-20_39 ansible_ssh_host=10.4.20.39
fentuan-bee-20_26 ansible_ssh_host=10.4.20.26
fentuan-bee-20_30 ansible_ssh_host=10.4.20.30
fentuan-bee-20_28 ansible_ssh_host=10.4.20.28
fentuan-bee-20_34 ansible_ssh_host=10.4.20.34
fentuan-bee-20_31 ansible_ssh_host=10.4.20.31
fentuan-bee-20_19 ansible_ssh_host=10.4.20.19
fentuan-bee-20_29 ansible_ssh_host=10.4.20.29
fentuan-bee-20_37 ansible_ssh_host=10.4.20.37
fentuan-bee-20_25 ansible_ssh_host=10.4.20.25
fentuan-bee-20_27 ansible_ssh_host=10.4.20.27
fentuan-bee-20_14 ansible_ssh_host=10.4.20.14
fentuan-bee-20_10 ansible_ssh_host=10.4.20.10
fentuan-bee-20_13 ansible_ssh_host=10.4.20.13
fentuan-bee-20_11 ansible_ssh_host=10.4.20.11
fentuan-bee-20_12 ansible_ssh_host=10.4.20.12
fentuan-bee-20_9 ansible_ssh_host=10.4.20.9
fentuan-bee-19_206 ansible_ssh_host=10.4.19.206
fentuan-bee-19_201 ansible_ssh_host=10.4.19.201
fentuan-bee-19_203 ansible_ssh_host=10.4.19.203
fentuan-bee-19_202 ansible_ssh_host=10.4.19.202
fentuan-bee-19_204 ansible_ssh_host=10.4.19.204
fentuan-bee-19_205 ansible_ssh_host=10.4.19.205
fentuan-bee-19_200 ansible_ssh_host=10.4.19.200
fentuan-bee-19_199 ansible_ssh_host=10.4.19.199
fentuan-bee-19_198 ansible_ssh_host=10.4.19.198
